server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 30
  write_timeout: 30
  environment: "production"

database:
  driver: "postgres"
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "password"
  database: "realtime_db"
  ssl_mode: "require"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  database: 0

logger:
  level: "info"
  format: "json"
  output: "stdout"
  time_format: "2006-01-02T15:04:05Z07:00"
