server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 30
  write_timeout: 30
  environment: "development"

database:
  driver: "postgres"
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "password"
  database: "realtime_db"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  database: 0

rabbitmq:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"
  vhost: "/"

jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  access_token_expires: 3600  # 1 hour in seconds
  refresh_token_expires: 604800  # 7 days in seconds

upload:
  max_file_size: 10485760  # 10MB
  allowed_types: ["image/jpeg", "image/png", "image/gif", "application/pdf", "text/plain"]
  upload_path: "./uploads"

logger:
  level: "info"
  format: "json"
  output: "stdout"
  time_format: "2006-01-02T15:04:05Z07:00"
